### ISSUE TITLE
ACTIVIDAD 7 :  CUESTIONARIO

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-ggar#1]
[CUESTIONARIO_PRACTICA 7.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipo-ggar/files/9974733/CUESTIONARIO_PRACTICA.7.pdf)

**Comment by ElisabetRD** [comment]
29%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
